innosoft_crm/Controllers/CallController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using innosoft_crm.Data;
using innosoft_crm.Helpers;
using innosoft_crm.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Font = iTextSharp.text.Font;
using Image = iTextSharp.text.Image;
using Rectangle = iTextSharp.text.Rectangle;

namespace innosoft_crm.Controllers
{
    public class CallController : Controller
    {
        #region TrnCall/TrnCallAction CRUD Functions
        //TrnCallList Json Result called by Jquery - Datatable Library for "Read" Function
        [HttpGet]
        public JsonResult TrnCallList(jQueryDataTableParamModel param)
        {
            var crmDc = new innosoft_crmDataContext();

            var trnCallList = from calls in crmDc.innosoft_trnCalls
                join customers in crmDc.innosoft_mstCustomers on calls.CustomerId equals customers.Id
                join products in crmDc.innosoft_mstProducts on calls.ProductId equals products.Id
                join callStatuses in crmDc.innosoft_mstCallStatus on calls.CallStatusId equals callStatuses.Id
                join staff in crmDc.innosoft_mstStaffs on calls.AssignedToId equals staff.Id
                let staffAssigned = staff.Name
                select new
                {
                    calls.Id,
                    calls.DateCalled,
                    StaffName = staffAssigned,
                    CustomerName = customers.Name,
                    ProductName = products.Product,
                    callStatuses.CallStatus
                };

            bool isCallDateSortable = Convert.ToBoolean(Request["bSortable_2"]);
            bool isStaffSortable = Convert.ToBoolean(Request["bSortable_3"]);
            bool isCustomerNameSortable = Convert.ToBoolean(Request["bSortable_4"]);
            bool isProductNameSortable = Convert.ToBoolean(Request["bSortable_5"]);
            bool isCallStatusSortable = Convert.ToBoolean(Request["bSortable_6"]);
            int sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);

            //Initial sort for jquery datatables, Sorted By Date in Descending Order 
            var sortedTrnCallListObIdDesc = from tcall in trnCallList
                orderby tcall.DateCalled descending
                select tcall;
            //Sort Date Ascending
            var sortedTrnCallListObDateAsc = from tcall in trnCallList
                orderby (sortColumnIndex == 2 && isCallDateSortable ? tcall.DateCalled : null) ascending
                select tcall;
            //Sort Date Descending
            var sortedTrnCallListObDateDesc = from tcall in trnCallList
                orderby (sortColumnIndex == 2 && isCallDateSortable ? tcall.DateCalled : null) descending
                select tcall;
            //Sort by any field selected except for date in ascending order
            var sortedTrnCallListAsc = from tcall in trnCallList
                orderby (sortColumnIndex == 3 && isStaffSortable
                    ? tcall.StaffName
                    : sortColumnIndex == 4 && isCustomerNameSortable
                        ? tcall.CustomerName
                        : sortColumnIndex == 5 && isProductNameSortable
                            ? tcall.ProductName
                            : sortColumnIndex == 6 && isCallStatusSortable
                                ? tcall.CallStatus
                                : "") ascending
                select tcall;
            //Sort by any field selected except for date in descending order
            var sortedTrnCallListDesc = from tcall in trnCallList
                orderby (sortColumnIndex == 3 && isStaffSortable
                    ? tcall.StaffName
                    : sortColumnIndex == 4 && isCustomerNameSortable
                        ? tcall.CustomerName
                        : sortColumnIndex == 5 && isProductNameSortable
                            ? tcall.ProductName
                            : sortColumnIndex == 6 && isCallStatusSortable
                                ? tcall.CallStatus
                                : "") descending
                select tcall;

            string sortDirection = Request["sSortDir_0"];
            //Sort Evaluation
            var sortedTrnCallList = sortDirection == "asc" && sortColumnIndex == 2
                ? sortedTrnCallListObDateAsc
                : sortDirection == "desc" && sortColumnIndex == 2
                    ? sortedTrnCallListObDateDesc
                    : sortDirection == "asc" && sortColumnIndex > 2
                        ? sortedTrnCallListAsc
                        : sortDirection == "asc" && sortColumnIndex == 0
                            ? sortedTrnCallListObIdDesc
                            : sortedTrnCallListDesc;

            //Initial return value if parameters in param are empty
            var filterTrnCallList = from sTcl in sortedTrnCallList
                select new
                {
                    sTcl.Id,
                    sTcl.DateCalled,
                    sTcl.StaffName,
                    sTcl.CustomerName,
                    sTcl.ProductName,
                    sTcl.CallStatus
                };

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                bool isCallDateSearchable = Convert.ToBoolean(Request["bSearchable_2"]);
                bool isStaffSearchable = Convert.ToBoolean(Request["bSearchable_3"]);
                bool isCustomerNameSearchable = Convert.ToBoolean(Request["bSearchable_4"]);
                bool isProductNameSearchable = Convert.ToBoolean(Request["bSearchable_5"]);
                bool isCallStatusSearchable = Convert.ToBoolean(Request["bSearchable_6"]);
                //The return value if parameters in param are not empty
                filterTrnCallList = from sTcl in sortedTrnCallList
                    where
                        isCallDateSearchable && sTcl.DateCalled.ToString().ToLower().Contains(param.sSearch.ToLower()) ||
                        isStaffSearchable && sTcl.StaffName.ToLower().Contains(param.sSearch.ToLower()) ||
                        isCustomerNameSearchable && sTcl.CustomerName.ToLower().Contains(param.sSearch.ToLower()) ||
                        isProductNameSearchable && sTcl.ProductName.ToLower().Contains(param.sSearch.ToLower()) ||
                        isCallStatusSearchable && sTcl.CallStatus.ToLower().Contains(param.sSearch.ToLower())
                    select new
                    {
                        sTcl.Id,
                        sTcl.DateCalled,
                        sTcl.StaffName,
                        sTcl.CustomerName,
                        sTcl.ProductName,
                        sTcl.CallStatus
                    };
            }
            //The display format of return
            var filteredTrnCallList = from sTcl in filterTrnCallList
                select new
                {
                    sTcl.Id,
                    DateCalled = String.Format("{0:MMM d yyyy}", sTcl.DateCalled.Value),
                    sTcl.StaffName,
                    sTcl.CustomerName,
                    sTcl.ProductName,
                    sTcl.CallStatus
                };

            var displayedTrnCallList = filteredTrnCallList.Skip(param.iDisplayStart).Take(param.iDisplayLength);
            //Value to list
            var result = displayedTrnCallList.ToList();
            //Final Return
            return Json(new
            {
                param.sEcho,
                iTotalRecords = crmDc.innosoft_trnCalls.Count(),
                iTotalDisplayRecords = filteredTrnCallList.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }

        //TrnCallDetail Json Result Called by Jquery - Knockout Library for "Read" Function
        [HttpGet]
        public JsonResult TrnCallDetail(Int64 id)
        {
            var crmDc = new innosoft_crmDataContext();
            var call = new TrnCall();

            innosoft_trnCall trnCallDetail = crmDc.innosoft_trnCalls.First(c => c.Id == id);

            call.Id = trnCallDetail.Id;
            call.DateCalled = DateTime.Parse(trnCallDetail.DateCalled.ToString()).ToShortDateString() == "" ? DateTime.Now.ToShortDateString() : DateTime.Parse(trnCallDetail.DateCalled.ToString()).ToShortDateString();
            call.CustomerId = Int32.Parse(trnCallDetail.CustomerId.ToString());
            call.ProductId = Int32.Parse(trnCallDetail.ProductId.ToString());
            call.Caller = trnCallDetail.Caller;
            call.Issue = trnCallDetail.Issue;
            call.CallStatusId = Int32.Parse(trnCallDetail.CallStatusId.ToString());
            call.AnsweredById = Int32.Parse(trnCallDetail.AnsweredById.ToString());
            call.AssignedtoId = Int32.Parse(trnCallDetail.AssignedToId.ToString());

            return Json(call, JsonRequestBehavior.AllowGet);
        }

        //TrnCallDetailMaxId Json Result Called by Jquery - Knockout Library for "Read" Function
        [HttpGet]
        public JsonResult TrnCallDetailMaxId()
        {
            var crmDc = new innosoft_crmDataContext();

            var trnCallDetailMaxId = (from i in crmDc.innosoft_trnCalls
                                        select i.Id).Max();

            return Json(trnCallDetailMaxId, JsonRequestBehavior.AllowGet);
        }

        //TrnCallDetail Json Result called by Jquery - Knockout Library for "Create" & "Update" Function
        public JsonResult TrnCallDetailSave(TrnCall call)
        {
            using (var crmDc = new innosoft_crmDataContext())
            {

                if (call.Id != 0)
                {
                    innosoft_trnCall trnCallDetail = crmDc.innosoft_trnCalls.Single(c => c.Id == call.Id);

                    trnCallDetail.DateCalled = DateTime.Parse(call.DateCalled);
                    trnCallDetail.CustomerId = call.CustomerId;

innosoft_crm/Views/Call/RepCallActionView.cshtml
@{
    ViewBag.Title = "Ticket Print Out";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

innosoft_crm/Views/Call/TrnCallListView.cshtml
@{
    ViewBag.Title = "Call List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container">
    <div class="row clearfix">
        <div class="col-md-12">
            <br />
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            &nbsp;
            <button type="button" id="CmdAdd" class="btn btn-labeled btn-primary" onclick="CmdAdd_onclick()">
                <span class="btn-label"><i class="glyphicon glyphicon-plus-sign"></i></span>Create
            </button>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="TrnCallListDatable" class="table condensed-table table-striped" >
                    <thead>
                        <tr>
                            <th colspan="1">
                            </th>
                            <th colspan="6" style="text-align:right"></th>
                        </tr>
                        <tr>
                            <th>Detail</th>
                            <th>Delete</th>
                            <th>Date Called</th>
                            <th>Staff</th>
                            <th>Customer</th>
                            <th>Product</th>
                            <th>Call Status</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-2.0.3.js" type="text/javascript"></script>

<script type="text/javascript" src="~/Scripts/jquery.dataTables.js"></script>
<script type="text/javascript" src="~/Scripts/bootstrap-dataTables-paging.js"></script>

<script src="~/Scripts/toastr.js" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        $('#TrnCallListDatable').dataTable(
            {
                "bServerSide": true,
                "bProcessing": true,
                "sAjaxSource": "@Url.Action("TrnCallList", "Call")",
                "aoColumns": [
                    {
                        "mData": "Id", "bSearchable": false,
                        "bSortable": false,
                        "sWidth": "40px",
                        "mRender": function (oObj) {
                            return '<button type="button" class="btn btn-labeled btn-primary" onclick="CmdDetail_onclick(' + oObj + ')"><span class="btn-label"><i class="glyphicon glyphicon-list"></i></span>Detail</button>';
                        }
                    },
                    {
                        "mData": "Id", "bSearchable": false,
                        "bSortable": false,
                        "sWidth": "40px",
                        "mRender": function (oObj) {
                            return '<button type="button" class="btn btn-labeled btn-danger" onclick="CmdDelete_onclick(' + oObj + ')"><span class="btn-label"><i class="glyphicon glyphicon-trash"></i></span>Delete</button>';
                        }
                    },
                    { "mDataProp": "DateCalled" },
                    { "mDataProp": "StaffName" },
                    { "mDataProp": "CustomerName" },
                    { "mDataProp": "ProductName" },
                    { "mDataProp": "CallStatus" }
                ]
         });
    });

    function CmdDelete_onclick(id) {
        if (confirm("Do you want to delete this call: " + id)) {
            var data = { 'id': id };
            $.post('@Url.Action("TrnCallListDelete", "Call")', data,
                function (retdata) {
                    if (retdata == true) {
                        location.href = 'TrnCallListView';
                        toastr.info("Record Deleted succesfully..");
                    }
                    else
                        toastr.error("Record Delete failed..");
                });
        }
    }

    function CmdDetail_onclick(id) {
        if (id > 0) {
            location.href = 'TrnCallDetailView?Id=' + id;
        }
    }

    function CmdAdd_onclick() {
        location.href = 'TrnCallDetailView';
    }
</script>